// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/testr.h"
#include <Rcpp.h>

using namespace Rcpp;

// serialize_error_handler
SEXP serialize_error_handler(SEXP e);
RcppExport SEXP testr_serialize_error_handler(SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(serialize_error_handler(e));
    return rcpp_result_gen;
END_RCPP
}
// WriteCapInfo_cpp
void WriteCapInfo_cpp(CharacterVector fname, SEXP args_env, SEXP retv_env);
RcppExport SEXP testr_WriteCapInfo_cpp(SEXP fnameSEXP, SEXP args_envSEXP, SEXP retv_envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type args_env(args_envSEXP);
    Rcpp::traits::input_parameter< SEXP >::type retv_env(retv_envSEXP);
    WriteCapInfo_cpp(fname, args_env, retv_env);
    return R_NilValue;
END_RCPP
}
